baseURL = "/"
languageCode = "en-us"
title = "Benjamin Simmonds"
theme = "terminal"
rssLimit = 100
paginate = 64
preserveTaxonomyNames = true
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

# [[menu.main]]
#     name = "Tags"
#     url = "/tags"
#     weight = -120
# 
# [[menu.main]]
#     name = "Categories"
#     url = "/categories"
#     weight = -130

[params]
    description = "bencode.net"
	themeColor = "green"
	fullWidthTheme = false
	centerTheme = true
	favicon = "images/doomguy-32x32.png"
    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[languages]
  [languages.en]
    title = "Ben Simmonds"
    subtitle = "Yet another blog about code and computers."
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Ben Simmonds"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
