baseURL = "/"
languageCode = "en-us"
title = "Ben Simmonds"
theme = "terminal"
rssLimit = 100
paginate = 64
preserveTaxonomyNames = true
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[menu]
[[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = -110
[[menu.main]]
    identifier = 'papers'
    name = 'Papers'
    url = '/papers'
    weight = -120

[params]
    description = "bencode.net"
	themeColor = "green"
	fullWidthTheme = false
	centerTheme = true
	favicon = "icons/android-chrome-512x512.png"

[params.twitter]
    creator = "bm4cs"
    site = "www.bencode.io"

[languages]
  [languages.en]
    title = "Ben Simmonds"
    subtitle = "A blog about code and computers"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Ben Simmonds"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "papers"
        name = "Papers"
        url = "/papers"
